version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
  
  worker:
    build: .
    command: node workers/requestWorker.js
    depends_on:
      - mongo
      - rabbitmq
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
